---
- name: sample_book
  hosts: dev-servers
  remote_user: root
  become: true
  tasks:
    - name: Run kubectl version
      command: kubectl version
      ignore_errors: yes
    - name: mysql deploy with kubernetes
      command: kubectl apply -f /var/lib/jenkins/workspace/DevOps-IOC/db-deployment.yaml
      ignore_errors: yes
    - name: SpringBoot deploy with kubernetes
      command: kubectl apply -f /var/lib/jenkins/workspace/DevOps-IOC/app-deployment.yaml
      ignore_errors: yes
